In [2]:
# features (1 sim, 0 não)
# pelo longo? 
# perna curta?
# faz auau?
porco1 = [0, 1, 0]
porco2 = [0, 1, 1]
porco3 = [1, 1, 0]

cachorro1 = [0, 1, 1]
cachorro2 = [1, 0, 1]
cachorro3 = [1, 1, 1]

# 1 => porco, 0 => cachorro
dados = [porco1, porco2, porco3, cachorro1, cachorro2, cachorro3]
classes = [1,1,1,0,0,0]

In [3]:
from sklearn.svm import LinearSVC

model = LinearSVC()
model.fit(dados, classes)

LinearSVC()

In [4]:
animal_misterioso = [1,1,1]
model.predict(animal_misterioso)

ValueError: Expected 2D array, got 1D array instead:
array=[1 1 1].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [5]:
animal_misterioso = [1,1,1]
model.predict([animal_misterioso])

array([0])

In [13]:
misterio1 = [1,1,1]
misterio2 = [1,1,0]
misterio3 = [0,1,1]

testes = [misterio1, misterio2, misterio3]
previsões = model.predict(testes)

In [14]:
testes_classes = [0, 1, 1]

In [21]:
previsões == testes_classes

array([ True,  True, False])

In [23]:
(previsões == testes_classes).sum()

2

In [25]:
corretos = (previsões == testes_classes).sum()
total = len(testes)
taxa_de_acerto = corretos/total
print("Taxa de acerto ", taxa_de_acerto * 100)

Taxa de acerto  66.66666666666666


In [28]:
from sklearn.metrics import accuracy_score
taxa_de_acerto = accuracy_score(testes_classes, previsões)
print("Taxa de acerto", taxa_de_acerto * 100)

Taxa de acerto 66.66666666666666


In [29]:
# mesmo código alterando nomenclaturas 

In [30]:
# 1 => porco, 0 => cachorro
treino_x = [porco1, porco2,  porco3, cachorro1, cachorro2, cachorro3]
treino_y = [1,1,1,0,0,0] # labels / etiquetas

In [31]:
from sklearn.svm import LinearSVC

model = LinearSVC()
model.fit(treino_x, treino_y)

LinearSVC()

In [32]:
animal_misterioso = [1,1,1]
model.predict([animal_misterioso])

array([0])

In [34]:
misterio1 = [1,1,1]
misterio2 = [1,1,0]
misterio3 = [0,1,1]

teste_x = [misterio1, misterio2, misterio3]
teste_y = [0, 1, 1]

previsoes = model.predict(teste_x)

In [35]:
corretos = (previsoes == teste_y).sum()
total = len(teste_x)
taxa_de_acerto = corretos/total 
print("Taxa de acerto: ", taxa_de_acerto * 100) # abaixo, ponto flutuante para casas decimais

Taxa de acerto:  66.66666666666666


In [36]:
from sklearn.metrics import accuracy_score

taxa_de_acerto = accuracy_score(teste_y, previsoes)
print("Taxa de acerto", taxa_de_acerto * 100)# abaixo, ponto flutuante para casas decimais

Taxa de acerto 66.66666666666666


In [37]:
corretos = (previsoes == teste_y).sum()
total = len(teste_x)
taxa_de_acerto = corretos/total 
print("Taxa de acerto %.2f " % (taxa_de_acerto * 100))

Taxa de acerto 66.67 


In [38]:
from sklearn.metrics import accuracy_score

taxa_de_acerto = accuracy_score(teste_y, previsoes)
print("Taxa de acerto %.2f " % (taxa_de_acerto * 100))

Taxa de acerto 66.67 
